## <p style="color:red;">Exercise 1:
<p style="color:red;">Create a new markdown cell and write first name in the format heading 1 and your family name in the format heading 2. Under your first and last name, add a new line with your student id. Make sure that your student id is bold.</p>

# Kevin
## Harianto
Student ID: **991602128**

## <p style="color:red;">Exercise 2:
<p style="color:red;"> a)Write a function that get a list of integers and append number 7 to the list. Print list values before and after calling function. 
<br> b) write a function that get a tuple of integeres and append number 7 to the tuple. Print the set values before and after calling function.)</p></br>

### Solution a)

In [20]:
list = [1, 2, 3]
print(list)
def appending_seven(list):
    list.append(7)
    return list
print(appending_seven(list))

[1, 2, 3]
[1, 2, 3, 7]


### Solution b)

In [27]:
tuples = (1, 2, 3)
print(tuples)
def appending_seven_for_tuple(tuple):
    tuple_add = tuple + (7,)
    return tuple_add
print(appending_seven_for_tuple(tuples))

(1, 2, 3)
(1, 2, 3, 7)


## <p style="color:red;">Exercise 3:
<p style="color:red;">
change the following function to a lamda function<br>
def my_fun(a):<br>
    &nbsp;&nbsp;&nbsp;&nbsp;return a**2<br>
my_fun(4)<br>

In [1]:
my_fun = lambda a: a**2
my_fun(4)

16

#### <p style="color:red;"> Exersise 4:
<p style="color:red;"> a)Create a numpy array of 20 items all 1 and name it A<br> b)Rearrange it by 4 rows and 5 columns
<br> c)Create a numpy array of 5 random numbers and name it B<br> d)Replace the last row of array A with B
<br> e)Do dot multiple of A with B and save it in a new array called C<br> f)Print every row of the array C by iterating every row<br> g)Print the value of row 2 and column 3 in array C</p>

a)

In [2]:
import numpy as np
A = np.array([1] * 20)

In [3]:
print(A)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


b)

In [4]:
A = A.reshape(4, 5)
print(A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


c)

In [5]:
B = np.random.randint(0, 100, 5)
B

array([59, 56, 65, 63, 74])

d)

In [6]:
A[-1] = B

In [7]:
A

array([[ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [59, 56, 65, 63, 74]])

e)

In [12]:
C = np.multiply(A, B) #using multiply due to how dot is not compatible with two different Dimensional Arrays.
C

array([[  59,   56,   65,   63,   74],
       [  59,   56,   65,   63,   74],
       [  59,   56,   65,   63,   74],
       [3481, 3136, 4225, 3969, 5476]])

f)

In [13]:
for row in C:
    print(row)

[59 56 65 63 74]
[59 56 65 63 74]
[59 56 65 63 74]
[3481 3136 4225 3969 5476]


g)

In [15]:
C[2,3]

63